feat: add initial configuration for middleware
noverde/faster-sam pull request #81
Opened 2024-01-16 14:39 UTC by gabriel-f-santos

### Contain
- [x] New feature
- [ ] Bugfix
- [ ] Tests
- [ ] Documentation
- [ ] Build/CI/CD
- [ ] Breaking changes
- [ ] Refactor
- [ ] Configuration changes
- [ ] Migrations

### Details
* Add initial configuration for authorization lambda

2024-01-16 15:46 UTC, Luis-Henrique requested changes

2024-01-16 15:46 UTC, Luis-Henrique commented on faster_sam/middleware.py
> +
Talvez adicionar um `e.g` para manter o padrão?

Veja um exemplo:

    e.g

    This example apply the middleware to transform the request path from "/foo/bar" to "/bar"
    by removing a specified part ("/foo").

2024-01-16 15:46 UTC, Luis-Henrique commented on faster_sam/middleware.py
> +    """
Aqui tambem colocamos os parâmetros do construtor.

Exemplo:

```
Parameters
    ----------
        app : ASGIApp
            Application instance the middleware is being registered to.
        path : str
            The part of the path to be removed from incoming requests.
```

2024-01-16 15:46 UTC, Luis-Henrique commented on faster_sam/middleware.py
> +        super().__init__(app, self.dispatch)
Aqui adicionaria uma breve sentença:

```
Initializes the LambdaAuthorizer.
```

2024-01-16 15:52 UTC, Luis-Henrique approved these changes

2024-01-16 18:07 UTC, gabriel-f-santos commented on faster_sam/middleware.py
> +class LambdaAuthorizer(BaseHTTPMiddleware):
Ajustado

2024-01-16 18:08 UTC, gabriel-f-santos commented on faster_sam/middleware.py
> +    def invoke_lambda_authorization(self, request: Request) -> Dict[str, any]:
Ajustado

2024-01-16 18:11 UTC, gabriel-f-santos commented on faster_sam/middleware.py
> +        return await call_next(request)
Sim, irei adicionar essa lógica e teste em um próximo Pr que ocorre a invocação da lambda.

Nos próximos pr poderíamos validar:

```
        response = self.invoke_lambda(request)

        body = json.loads(response["Payload"].read())

        if body["policyDocument"]["Statement"][0]["Effect"] == "Deny":
            return Response(
                content=json.dumps({"message": "Unauthorized"}),
                status_code=HTTPStatus.UNAUTHORIZED.value,
            )
        return await call_next(request)
```

2024-01-16 18:13 UTC, gabriel-f-santos commented on faster_sam/middleware.py
> +            )
Faz sentido. Duas verificações, uma da requisição e outra sobre conteúdo da autorização.

2024-01-17 17:50 UTC, julianolf commented on tests/test_middleware.py
Como foi dividido os módulos de middleware acho que os testes também deveriam.

2024-01-17 18:58 UTC, gabriel-f-santos commented on tests/test_middleware.py
Ajustado!

2024-01-23 21:34 UTC, Luis-Henrique submitted a review, later dismissed

2024-01-23 21:46 UTC, julianolf approved these changes

2024-01-23 21:47 UTC, Luis-Henrique approved these changes

2024-01-23 21:48 UTC, merged